---
- name: add rpm for python
  become: yes
  yum: name=https://centos7.iuscommunity.org/ius-release.rpm

- name: install python36
  become: yes
  yum:
    name='{{item}}'
    state=latest
  with_items:
    - python36u
    - python36u-libs
    - python36u-devel
    - python36u-pip

