---
- name: install mariadb
  become: yes
  yum:
    name='{{ item }}'
    state=latest
  with_items:
    - mariadb
    - mariadb-server
    - mariadb-devel
    - mariadb-libs
  
- name: start mariadb
  systemd: 
    name: mariadb
    state: started
    enabled: yes